# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4e0003570d8742bfb3f12294251d27fdee3cfb9aad82c163b0b0ccd1c41a801bbdd1fa5b7868dd52500b1b81b80229813826bd3e470e7f633909572199bbc0a8

test:
  secret_key_base: 4cc2a9ce492b81761604eeb9c86f3428907b5abbcc0b8385df9ea2c49e6677001bad647b4de46bb579c68446c38700e9818eed085e89e9a0542aae8fed740efe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
